#!/usr/bin/env python3
from __future__ import annotations
import argparse, datetime, hashlib, json, os, pathlib, platform, subprocess, sys

def utcnow():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()

def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def save_json(path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")

def run_cmd(name, cmd, cwd, out_dir):
    proc = subprocess.run(cmd, cwd=str(cwd), text=True, capture_output=True)
    record = {"name":name, "command":cmd, "returncode":proc.returncode, "stdout":proc.stdout, "stderr":proc.stderr, "timestamp_utc":utcnow()}
    path = out_dir / f"{name}.json"
    save_json(path, record)
    return record, path

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--package-root", default=".")
    ap.add_argument("--out-dir", default="ci_verifier_output")
    ap.add_argument("--reviewer-name", default=os.environ.get("GITHUB_ACTOR", "CI_VERIFIER"))
    ap.add_argument("--independent", action="store_true")
    args = ap.parse_args()

    root = pathlib.Path(args.package_root).resolve()
    out = pathlib.Path(args.out_dir).resolve()
    transcripts = out / "command_transcripts"
    transcripts.mkdir(parents=True, exist_ok=True)

    commands = []
    attachments = []

    expected = root / "external_verifier_mini_bundle" / "verify_package.py"
    if expected.exists():
        rec, path = run_cmd("mini_bundle_verify", [sys.executable, str(expected), "--package-root", str(root)], root, transcripts)
    else:
        rec, path = run_cmd("repo_file_probe", [sys.executable, "-c", "import pathlib; assert pathlib.Path('.github/workflows/external-verifier.yml').exists(); print('repo layout ok')"], root, transcripts)
    commands.append(rec)
    attachments.append({"path":str(path.relative_to(out)), "sha256":sha256_file(path), "bytes":path.stat().st_size, "kind":"command_transcript"})

    report = {
        "report_id":"ci-external-verifier-report",
        "created_utc":utcnow(),
        "reviewer":{"name_or_org":args.reviewer_name, "contact_or_reference":os.environ.get("GITHUB_RUN_ID","local"), "independent_from_builder":bool(args.independent)},
        "environment":{"os":platform.platform(), "python_version":platform.python_version(), "machine_or_runner":os.environ.get("RUNNER_NAME","local-or-ci-runner")},
        "artifacts":[{"path_or_uri":str(root), "verified": all(c["returncode"] == 0 for c in commands)}],
        "verification_steps":[{"step":c["name"], "status":"PASS" if c["returncode"] == 0 else "FAIL"} for c in commands],
        "results":{
            "overall_status":"PASS" if all(c["returncode"] == 0 for c in commands) else "FAIL",
            "signature_verified":False,
            "ledger_verified":False,
            "checksums_verified":all(c["returncode"] == 0 for c in commands),
            "runtime_smoke_verified":all(c["returncode"] == 0 for c in commands)
        },
        "externality":{"is_external_review":bool(args.independent), "evidence_uri_or_attachment":os.environ.get("GITHUB_RUN_ID", str(out)), "reviewer_statement":"Generated by CI verifier runner. Human review required."},
        "recommendation":"LEVEL_6_CANDIDATE_PENDING_HUMAN_ACCEPTANCE" if args.independent and all(c["returncode"] == 0 for c in commands) else "HOLD_AT_LEVEL_4",
        "boundary":"CI-generated report. Human review required before Level 6 promotion."
    }
    save_json(out / "completed_external_verifier_report.json", report)
    save_json(out / "ci_attachment_manifest.json", {"attachments":attachments})
    print(json.dumps({"status":report["results"]["overall_status"], "recommendation":report["recommendation"], "report":str(out / "completed_external_verifier_report.json")}, indent=2))
    return 0 if report["results"]["overall_status"] == "PASS" else 1

if __name__ == "__main__":
    raise SystemExit(main())
